config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins, skip: [:registrations], controllers: {sessions: 'admins/sessions'}

  namespace :admin do
    root to: "home#index"
    resources :admins
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :phone, :name, :avatar, presence: true

  has_one_attached :avatar
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < AdminController
  before_action :set_admin, only: [:edit, :update, :destroy]

  def index
    @admins = Admin.order(id: :desc)
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(form_params)

    if @admin.save
      redirect_to admin_admins_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    params = form_params.to_h
    params = params.except!(:password, :password_confirmation) if params[:password].blank?

    if @admin.update(params)
      redirect_to admin_admins_path
    else
      render :edit
    end
  end

  def destroy
    @admin.destroy
    redirect_to admin_admins_path
  end

  private

  def form_params
    params.require(:admin).permit(:name, :email, :password, :password_confirmation)
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController

  def index
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin

  def authenticate_admin
    redirect_to new_admin_session_path unless current_admin?
  end


  def current_admin?
    if current_admin.present?
      true
    else
      false
    end
  end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController

  def after_sign_out_path_for(admin)
    new_admin_session_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/admins/_form.html.erb
<div class="container">
  <div class="card" style="background-color:#f6f6f6;">
    <div class="card-body">
      <%= form_with(model: [:admin, admin], local: true) do |f| %>
        <%= render "layouts/form_errors", record: admin %>
        <div class="form-group">
          <label>Nome</label>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Email</label>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="form-row">
          <div class="col-6">
            <div class="form-group">
              <label>Senha</label>
              <%= f.password_field :password, class: "form-control" %>
            </div>
          </div>
          <div class="col-6">
            <div class="form-group">
              <label>Confirmar Senha</label>
              <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
        <%= link_to "Voltar", admin_admins_path, class: "btn btn-secondary ml-3" %>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/admins/edit.html.erb
<h2>Editar Administrador #<%= @admin.id%> </h2>

<%= render "form", admin: @admin %>

app/views/admin/admins/index.html.erb
<div class="container">
  <%= link_to("Novo Administrador", new_admin_admin_path, class: "btn btn-success mb-4") %>
  <h4>Admins</h4><br>
  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Criado em</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @admins.each do |admin| %>
      <tr>
        <th scope="row"><%= admin.id %></th>
        <td><%= admin.name %></td>
        <td><%= admin.email %></td>
        <td><%= admin.created_at %></td>
        <td><%= link_to "Editar", edit_admin_admin_path(admin), class: "btn btn-warning btn-sm" %></td>
        <td><%= button_to "Deletar", admin_admin_path(admin), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-sm" %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/admins/new.html.erb
<div class="container">
  <h1>Novo Administrador</h1>
</div>

<%= render "form", admin: @admin %>

app/views/admin/home/index.html.erb
<h1> Seja bem vindo! </h1>

app/views/layouts/_form_errors.html.erb
<% if record && record.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= t('.error_on_save') %></h4>
    <ul>
    <% record.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<% content_for :content do %>
  <%= render "layouts/admin/header" %>
  <div class="container mt-5">
    <%= yield %>
  </div>
<% end %>


<%= render template: "layouts/application" %>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container">
    <ul class="navbar-nav">
      <li class="nav-item <%= current_page?(admin_root_path)? "active" : "" %>">
        <%= link_to("Home", admin_root_path, class: "nav-link") %>
      </li>
      <li class="nav-item" <%= current_page?(admin_admins_path)? "active" : "" %>>
        <%= link_to("Administradores", admin_admins_path, class: "nav-link") %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Usuários</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Posts</a>
      </li>
    </ul>
    <div class="nav-item d-flex">
      <ul class="navbar-nav">
        <li class="nav-item">
          <div class="py-2 mr-4" style="color:#fff;"><%= current_admin.email %></div>
        </li>
        <li class="nav-item" style="opacity:[1];">
          <%= button_to "Sair", destroy_admin_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="height:100%">
  <head>
    <title>SocialNetwork</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="height:100%;">
    <%= content_for?(:content) ? yield(:content) : yield %>
  </body>
</html>